Add SSH key exists

diff --git a/arm-image-installer b/arm-image-installer
--- a/arm-image-installer
+++ b/arm-image-installer
@@ -301,6 +301,12 @@ if [ ! -e "$MEDIA" ]; then
 	exit 1
 fi
 
+# SSH key exists
+if [ ! -f "$SSH_KEY" ] && [ "$SSH_KEY" != "" ]; then
+	echo "Error: $SSH_KEY not found! Please choose an existing SSH key."
+	exit 1
+fi
+
 # Last chance to back out
 echo ""
 echo "====================================================="
